#pragma config(Motor,  port2,           MotorOut1,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           MotorIn1,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           MotorIn2,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           MotorOut2,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                    - Single Joystick Control -                                     *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses a single joystick, either right or left (this is configurable below) to drive   *|
|*  the robot.                                                                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{

  while(1 == 1)
  {
    motor[MotorOut1] = (vexRT[Ch2]);  // (y + x)/2
    motor[MotorOut2] = motor[MotorOut1];
    motor[MotorIn1] = (vexRT[Ch2]);  // (y + x)/2
    motor[MotorIn2] = motor[MotorIn1];
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
