#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           InsideMotor,   tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           OutsideMotor,  tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speeds[4]={0,1000,2000,3000};
	int index;
	while(true){
		if(vexRT[Btn5U]){
			index++;
			if(index>3){
				index=0;
			}
			setMotorRPM(speeds[index]);
		}
		if(vexRT[Btn5D]){
			index--;
			if(index<0){
				index=3;
			}
			setMotorRPM(speeds[index]);
		}
	}

}

void setMotorRPM(int speed){
			motor[InsideMotor] = RPMtoPower(speed);
			motor[OutsideMotor] = RPMtoPower(speed);
}
int RPMtoPower(int rpm){
	//Equation derived from logarithmic fit line for
	//values obtained from testMotors()
	return pow(1.0000000547282,10000*rpm+49825517);
}
