#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    lineTracker,    sensorLineFollower)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LRWheel,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Inside1,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           Inside2,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           Outside1,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Outside2,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Feeder,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LFWheel,       tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port8,           RRWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RFWheel,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Notes for noobs
/*----------------------------------------------------------------------------------------------------*\
|*                                    - Single Joystick Control -                                     *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses a single joystick, either right or left (this is configurable below) to drive   *|
|*  the robot.                                                                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

int Presets[4] = {0,55, 85,127};

//These variables track the robots position and orientation
//Useful for any future decisions to veer off track or calculate routes
float locX;
float locY;
float rotation;

//Distance is in inches
//Wheels are 4 inches, so one complete rotation moves the bot 4 inches




void freeze()//for the wheels
{
	motor[LFWheel] = 0;
	motor[LRWheel] = 0;
	motor[RFWheel] = 0;
	motor[RRWheel] = 0;
}



void move(int dist)
{
	int distance = abs(dist);
	if(dist>0){
	motor[LFWheel] = 127;
	motor[LRWheel] = 127;
	motor[RFWheel] = 127;
	motor[RRWheel] = 127;
	}else{
	motor[LFWheel] = -127;
	motor[LRWheel] = -127;
	motor[RFWheel] = -127;
	motor[RRWheel] = -127;
	}
	nMotorEncoder[LFWheel] = 0;
	while(abs(nMotorEncoder[LFWheel])/627.2<distance/(4.0*PI)){
		wait1Msec(10);
	}

	locX+=cosDegrees(rotation)*distance;
	locY+=sinDegrees(rotation)*distance;
	freeze();
}

void rightTurn (int angle)
{

	motor[LFWheel] = 127;
	motor[LRWheel] = 127;
	motor[RFWheel] = -127;
	motor[RRWheel] = -127;

	nMotorEncoder[LFWheel] = 0;
	while(nMotorEncoder[LFWheel]/627.2<(3.125*(angle/360.0))){
		wait1Msec(10);
	}

	rotation = (rotation + angle) % 360;
	freeze();
}

void leftTurn (int angle)
{

	motor[LFWheel] = -127;
	motor[LRWheel] = -127;
	motor[RFWheel] = 127;
	motor[RRWheel] = 127;

	nMotorEncoder[LFWheel] = 0;
	while(abs(nMotorEncoder[LFWheel])/627.2<(3.125*(angle/360.0))){
		wait1Msec(10);
	}

	rotation = (rotation - angle) % 360;
	freeze();
}





void fly(int speedElement)
{
	if(!((speedElement < 0) || (speedElement > 4)))
	{
		motor[Inside1] = Presets[speedElement];
		motor[Inside2] = Presets[speedElement];
		motor[Outside1] = Presets[speedElement];
		motor[Outside2] = Presets[speedElement];
	}
}


void adjustRight(){

	motor[LFWheel] = 30;
	motor[LRWheel] = 30;
	motor[RFWheel] = -30;
	motor[RRWheel] = -30;
	while(true){
		if(SensorValue(lineTracker)<2850){
		freeze();
		break;
		}
	}

}

void adjustLeft(){

	motor[LFWheel] = -30;
	motor[LRWheel] = -30;
	motor[RFWheel] = 30;
	motor[RRWheel] = 30;
	while(true){
		if(SensorValue(lineTracker)<2850){
		freeze();
		break;
		}
	}
}


void intake(bool on)
{
	motor[Feeder] = (on) ? (127) : (0);
}


void rest()//all motors on robot stop
{
	freeze();
	fly(0);
	intake(false);
}

task main()
{
	while(true)
	{
		if(vexRT(Btn8U)){
		move(25);
		leftTurn(45);
		fly(3);
		intake(true);
		move(10);
		intake(false);
		move(20);
		intake(true);
		adjustRight();
		wait10Msec(500);
		rest();
		}
	}
}
