#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           Feeder,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Inside1,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           Inside2,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           Outside1,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Outside2,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           LRWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LFWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RRWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RFWheel,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Robot A Driver Control program
task main()
{

	// Set the motors initially
	int Presets[4] = {0, 55, 85, 127};
	int currentPreset = 0;
	motor[Inside1] = Presets[currentPreset];
	motor[Inside2] = motor[Inside1];
	motor[Outside1] = motor[Inside1];
	motor[Outside2] = motor[Inside1];


	while(true)
	{
		// Flywheel Speed
	 if(vexRT(Btn8U))
		currentPreset = 0;
	 else if (vexRT(Btn8R))
	  currentPreset = 1;
	 else if (vexRT(Btn8D))
	   currentPreset = 2;
	 else if (vexRT(Btn8L))
	   currentPreset = 3;

		motor[Inside1] = Presets[currentPreset];
		motor[Inside2] = motor[Inside1];
		motor[Outside1] = motor[Inside1];
		motor[Outside2] = motor[Inside1];

		// Fit the input to an exponential curve
		// Squares are always positive, so a ternary operator is needed for negative numbers
		// The abs is just in case we decide to go with odd exponents or even roots (like 3/2)
		// We devide by 128 because the program can theoretically reach -128
		int verticalL = pow(abs(vexRT(Ch3))/128.0,2.0)*127.0 *((vexRT(Ch3)>0)?(1):(-1));
		int verticalR = pow(abs(vexRT(Ch2))/128.0,2.0)*127.0 *((vexRT(Ch2)>0)?(1):(-1));

		// Move Robot
	  motor[LRWheel] = verticalL;
	  motor[LFWheel] = motor[LRWheel];
    motor[RRWheel] = verticalR;
    motor[RFWheel] = motor[RRWheel];

    //Feeder control
	  if(vexRT(Btn6U))
	     motor[Feeder] = 127;
	  else if(vexRT(Btn5U))
			 motor[Feeder] = -127;
		else
	 	   motor[Feeder] = 0;

	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
