#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           LRWheel,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LFFlywheel,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           RFFlywheel,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           LRFlywheel,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RRFlywheel,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Feeder,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LFWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RRWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RFWheel,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// PID Control Definitions
#define PID_SENSOR_INDEX    I2C_1
#define PID_SENSOR_SCALE    1
#define PID_MOTOR_INDEX    LFFlywheel
#define PID_MOTOR_SCALE    (-1)
#define PID_DRIVE_MAX        127
#define PID_DRIVE_MIN        (-127)
#define PID_INTEGRAL_LIMIT   50

// PID Control Global Variables
float  			 pid_Kp = 2.0;
float  			 pid_Ki = 0.04;
float 			 pid_Kd = 0.0;
static int 	 pidRunning = 1;
static float pidRequestedValue;

task pidController()
{
		float  pidSensorCurrentValue;
    float  pidError;
    float  pidLastError;
    float  pidIntegral;
    float  pidDerivative;
    float  pidDrive;

    // If we are using an encoder then clear it
    if( SensorType[ PID_SENSOR_INDEX ] == sensorQuadEncoderOnI2CPort )
        SensorValue[ PID_SENSOR_INDEX ] = 0;

    // Init the variables
    pidLastError  = 0;
    pidIntegral   = 0;

    while( true )
        {
        // Is PID control active ?
        if( pidRunning )
            {
            // Read the sensor value and scale
            pidSensorCurrentValue = SensorValue[ PID_SENSOR_INDEX ] * PID_SENSOR_SCALE;

            // calculate error
            pidError = pidSensorCurrentValue - pidRequestedValue;

            // integral - if Ki is not 0
            if( pid_Ki != 0 )
                {
                // If we are inside controllable window then integrate the error
                if( abs(pidError) < PID_INTEGRAL_LIMIT )
                    pidIntegral = pidIntegral + pidError;
                else
                    pidIntegral = 0;
                }
            else
                pidIntegral = 0;

            // calculate the derivative
            pidDerivative = pidError - pidLastError;
            pidLastError  = pidError;

            // calculate drive
            pidDrive = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

            // limit drive
            if( pidDrive > PID_DRIVE_MAX )
                pidDrive = PID_DRIVE_MAX;
            if( pidDrive < PID_DRIVE_MIN )
                pidDrive = PID_DRIVE_MIN;

            // send to motor
            motor[ PID_MOTOR_INDEX ] = pidDrive * PID_MOTOR_SCALE;
            }
        else
            {
            // clear all
            pidError      = 0;
            pidLastError  = 0;
            pidIntegral   = 0;
            pidDerivative = 0;
            motor[ PID_MOTOR_INDEX ] = 0;
            }

        // Run at 50Hz
        wait1Msec( 25 );
        }
}

//Robot A Driver Control program
task main()
{

	// Set the motors initially
	int Presets[4] = {0, 250, 700, 1000};
	int currentPreset = 0;
	motor[LFFlywheel] = 0;
	StartTask(pidController);
	motor[RFFlywheel] = motor[LFFlywheel];
	motor[LRFlywheel] = motor[LFFlywheel];
	motor[RRFlywheel] = motor[LFFlywheel];


	while(true)
	{

		// Flywheel Speed
	 if(vexRT(Btn8U))
		currentPreset = 0;
	 else if (vexRT(Btn8R))
	  currentPreset = 1;
	 else if (vexRT(Btn8D))
	   currentPreset = 2;
	 else if (vexRT(Btn8L))
	   currentPreset = 3;

	  pidRequestedValue = Presets[currentPreset];
		motor[RFFlywheel] = motor[LFFlywheel];
		motor[LRFlywheel] = motor[LFFlywheel];
		motor[RRFlywheel] = motor[LFFlywheel];

		// Fit the input to an exponential curve
		// Squares are always positive, so a ternary operator is needed for negative numbers
		// The abs is just in case we decide to go with odd exponents or even roots (like 3/2)
		// We devide by 128 because the program can theoretically reach -128
		int verticalL = pow(abs(vexRT(Ch3))/128.0,2.0)*127.0 *((vexRT(Ch3)>0)?(1):(-1));
		int verticalR = pow(abs(vexRT(Ch2))/128.0,2.0)*127.0 *((vexRT(Ch2)>0)?(1):(-1));

		// Move Robot
	  motor[LRWheel] = verticalL;
	  motor[LFWheel] = motor[LRWheel];
    motor[RRWheel] = verticalR;
    motor[RFWheel] = motor[RRWheel];

    //Feeder control
	  if(vexRT(Btn6U))
	     motor[Feeder] = 127;
	  else if(vexRT(Btn5U))
			 motor[Feeder] = -127;
		else
	 	   motor[Feeder] = 0;

	 	   wait10Msec(1);
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
