#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  Feeder,         sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           Inside1,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           Inside2,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           Outside1,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Outside2,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           LRWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LFWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RRWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RFWheel,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Notes for noobs
/*----------------------------------------------------------------------------------------------------*\
|*                                    - Single Joystick Control -                                     *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses a single joystick, either right or left (this is configurable below) to drive   *|
|*  the robot.                                                                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{

	// Set the motors initially
	int Presets[4] = {0, 55, 85, 127};
	int currentPreset = 0;
	motor[Inside1] = Presets[currentPreset];
	motor[Inside2] = motor[Inside1];
	motor[Outside1] = motor[Inside1];
	motor[Outside2] = motor[Inside1];


	while(true)
	{
		// Flywheel Speed
	 if(vexRT(Btn8U))
		currentPreset = 0;
	 else if (vexRT(Btn8R))
	  currentPreset = 1;
	 else if (vexRT(Btn8D))
	   currentPreset = 2;
	 else if (vexRT(Btn8L))
	   currentPreset = 3;

		motor[Inside1] = Presets[currentPreset];
		motor[Inside2] = motor[Inside1];
		motor[Outside1] = motor[Inside1];
		motor[Outside2] = motor[Inside1];

		//Fit the input to an exponential curve
		//Squares are always positive, so a ternary operator is needed for negative numbers
		//The abs is just in case we decide to go with odd exponents
		int verticalL = abs(pow(vexRT(Ch3)/127.0,2.0))*127.0 *((vexRT(Ch3)>0)?(-1):(1));
		int verticalR = abs(pow(vexRT(Ch2)/127.0,2.0))*127.0 *((vexRT(Ch2)>0)?(-1):(1));

		// Move Robot
	  motor[LRWheel] = verticalL;
	  motor[LFWheel] = motor[LRWheel];
    motor[RRWheel] = verticalR;
    motor[RFWheel] = motor[RRWheel];

	   if(vexRT(Btn6U))
	     SensorValue[Feeder] = 1;
	 	 else if (vexRT(Btn5U))
	     SensorValue[Feeder] = 0;

	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
