#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  Feeder,         sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           Inside1,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           Inside2,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           Outside1,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Outside2,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           LRWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LFWheel,       tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port8,           RRWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RFWheel,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Notes for noobs
/*----------------------------------------------------------------------------------------------------*\
|*                                    - Single Joystick Control -                                     *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses a single joystick, either right or left (this is configurable below) to drive   *|
|*  the robot.                                                                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

int Presets[4] = {0,55, 85,127};

void move(int speed)//this can be used forward or backward movement
{
	motor[LFWheel] = speed;
	motor[LRWheel] = speed;
	motor[RFWheel] = speed;
	motor[RRWheel] = speed;
}

void leftTurn (int angle)
{
	motor[LFWheel] = 127;
	motor[LRWheel] = 127;
	motor[RFWheel] = -127;
	motor[RRWheel] = -127;
	nMotorEncoder[LFWheel] = 0;
	while(nMotorEncoder[LFWheel]/627.2<(3.125*(angle/360.0))){
	wait1Msec(10);
		if(vexRT(Btn8U)){
			break;
		}
	}
}

void rightTurn (int time)
{
	motor[LFWheel] = -127;
	motor[LRWheel] = -127;
	motor[RFWheel] = 127;
	motor[RRWheel] = 127;
	wait1Msec(time);
}



void freeze()//for the wheels
{
	motor[LFWheel] = 0;
	motor[LRWheel] = 0;
	motor[RFWheel] = 0;
	motor[RRWheel] = 0;
}

void fly(int speedElement)
{
	if(!((speedElement < 0) || (speedElement > 4)))
	{
		motor[Inside1] = Presets[speedElement];
		motor[Inside2] = Presets[speedElement];
		motor[Outside1] = Presets[speedElement];
		motor[Outside2] = Presets[speedElement];
	}
}

void intake(int speed)
{
	motor[Feeder] = speed;
}

void rest()//all motors on robot stop
{
	freeze();
	fly(0);
	intake(0);
}

task main()
{
	while(true)
	{
		if(vexRT(Btn5D))
		{
			move(-127);
			wait1Msec(1000);
			freeze();
		}
		else if(vexRT(Btn5U))
		{
			move(127);
			wait1Msec(1000);
			freeze();
		}
		else if(vexRT(Btn7U))
		{
			leftTurn(360);
			freeze();
		}
		else if(vexRT(Btn7D))
		{
			rightTurn(2100);
			freeze();
		}

		else if(vexRT(Btn6U))
		{
			fly(3);
			wait1Msec(3000);
		}
		else if(vexRT(Btn6D))
		{
			intake(127);
		}
		else
		{
			rest();
		}
	}
}
