#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           LFW,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RFW,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RRW,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LRW,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           REF,           tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port6,           RF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LF,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           I1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           I2,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Presets[4] = {0,55, 85,127};

//These variables track the robots position and orientation
//Useful for any future decisions to veer off track or calculate routes
float locX;
float locY;
float rotation;

//Distance is in inches
//Wheels are 4 inches, so one complete rotation moves the bot 4 inches




void freeze()//for the wheels
{
	motor[LFW] = 0;
	motor[LRW] = 0;
	motor[RFW] = 0;
	motor[RRW] = 0;
}



void move(int dist)
{
	int distance = abs(dist);
	if(dist>0){
	motor[LFW] = 127;
	motor[LRW] = 127;
	motor[RFW] = 127;
	motor[RRW] = 127;
	}else{
	motor[LFW] = -127;
	motor[LRW] = -127;
	motor[RFW] = -127;
	motor[RRW] = -127;
	}
	nMotorEncoder[LFW] = 0;
	while(abs(nMotorEncoder[LFW])/627.2<distance/(4.0*PI)){
		wait1Msec(10);
	}

	locX+=cosDegrees(rotation)*distance;
	locY+=sinDegrees(rotation)*distance;
	freeze();
}

void rightTurn (int angle)
{

	motor[LFW] = 127;
	motor[LRW] = 127;
	motor[RFW] = -127;
	motor[RRW] = -127;

	nMotorEncoder[LFW] = 0;
	while(nMotorEncoder[LFW]/627.2<(3.0*(angle/360.0))){
		wait1Msec(10);
	}

	rotation = (rotation + angle) % 360;
	freeze();
}

void leftTurn (int angle)
{

	motor[LFW] = -127;
	motor[LRW] = -127;
	motor[RFW] = 127;
	motor[RRW] = 127;

	nMotorEncoder[LFW] = 0;
	while(abs(nMotorEncoder[LFW])/627.2<(3.0*(angle/360.0))){
		wait1Msec(10);
	}

	rotation = (rotation - angle) % 360;
	freeze();
}





void fly(int speedElement)
{
	if(!((speedElement < 0) || (speedElement > 4)))
	{
		motor[RF] = Presets[speedElement];
		motor[REF] = Presets[speedElement];
		motor[LF] = Presets[speedElement];
	}
}

/*
void adjustRight(){

	motor[LFW] = 30;
	motor[LRW] = 30;
	motor[RFW] = -30;
	motor[RRW] = -30;
	while(true){
		if(SensorValue(lineTracker)<2850){
		freeze();
		break;
		}
	}

}

void adjustLeft(){

	motor[LFW] = -30;
	motor[LRW] = -30;
	motor[RFW] = 30;
	motor[RRW] = 30;
	while(true){
		if(SensorValue(lineTracker)<2850){
		freeze();
		break;
		}
	}
}
*/


void intake(bool on)
{
	motor[I2] = motor[I1] = (on) ? (127) : (0);

}


void rest()//all motors on robot stop
{
	freeze();
	fly(0);
	intake(false);
}

task main()
{
	while(true)
	{
		if(VexRT(Btn5U)){
		leftTurn(1);
		wait10Msec(100);
		}
		if(VexRT(Btn6U)){
		rightTurn(1);
		wait10Msec(100);
		}
		if(VexRT(Btn8U)){
		move(2);
		wait10Msec(100);
		}
		if(VexRT(Btn8D)){
		move(-2);
		wait10Msec(100);
		}

		if(VexRT(Btn7U)){
		rightTurn(360);
		}


		if(vexRT(Btn8R)){
		rightTurn(2);
		move(20);
		leftTurn(10);
		move(30);
		intake(true);
		fly(3);
		wait10Msec(1000);
		rest();
		}
	}
}
