#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    RightLF,        sensorLineFollower)
#pragma config(Sensor, in2,    LeftLF,         sensorLineFollower)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LFW,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RFW,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RRW,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LRW,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           REF,           tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port6,           RF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LF,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           I1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           I2,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

// Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(45)
#pragma userControlDuration(115)
#include "Vex_Competition_Includes.c"

/////////////////////////////////////////////////////////////////////////////////////////
//                       				 Function Stubs
/////////////////////////////////////////////////////////////////////////////////////////

void freeze();
void move(int dist);
void rightTurn(int angle);
void leftTurn(int angle);
void leftms(int ms);
void rightms(int ms);
void forwardms(int ms);
void backms(int ms);
void fly(int speedElement);
void adjustRight();
void adjustLeft();
void intake(bool on);
void rest();
void flyspeed(int speed);

/////////////////////////////////////////////////////////////////////////////////////////
//                       			  Global Variables
/////////////////////////////////////////////////////////////////////////////////////////

// **** PLEASE DO NOT TOUCH THIS SECTION ****
int Presets[4] = {0, 54, 69, 77};
// **** PLEASE DO NOT TOUCH THIS SECTION ****

// These variables track the robots position and orientation
// Useful for any future decisions to veer off track or calculate routes
float locX;
float locY;
float rotation;
int currentPreset = 0;
static float drivespeed = 0;

/////////////////////////////////////////////////////////////////////////////////////////
//                          Pre-Autonomous Functions
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
}

/////////////////////////////////////////////////////////////////////////////////////////
//                                 Autonomous Task
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
		// Set the motors initially
		currentPreset = 0;
		fly(currentPreset);

		// Right turn angles
		int Rdegrees_45 = 350;
		int Rdegrees_90 = 650;
		int Rdegrees_180 = 1238;

		// Left turn angles
		int Ldegrees_45 = 370
		int Ldegrees_90 = 660;
		int Ldegrees_180 = 1288;

		// Sample code
		// rightms(Rdegrees_45);
		// wait10Msec(85);

		rightms(Rdegrees_45);
		wait1Msec(850);
		forwardms(2300);
		wait1Msec(850);
		rightms(Rdegrees_45);
		wait1Msec(850);
		forwardms(1000);
		wait1Msec(850);
		leftms(Ldegrees_45+45);
		wait1Msec(850);

		flyspeed(Presets[2]+5);
		wait1Msec(800);
		intake(true);
		wait1Msec(1000);
		intake(false);
		wait1Msec(3000);
		intake(true);
		wait1Msec(1000);
		intake(false);


		/*if(vexRT(Btn5U))
		{
			leftTurn(1);
			wait10Msec(100);
		}
		if(vexRT(Btn6U))
		{
			rightTurn(1);
			wait10Msec(100);
		}
		if(vexRT(Btn8U))
		{
			move(2);
			wait10Msec(100);
		}
		if(vexRT(Btn8D))
		{
			move(-2);
			wait10Msec(100);
		}

		if(vexRT(Btn7U))
		{
			rightTurn(360);
		}

		if(vexRT(Btn8R))
		{
			rightTurn(2);
			move(20);
			leftTurn(10);
			move(30);
			intake(true);
			fly(3);
			wait10Msec(1000);
			rest();
		}*/
}

/////////////////////////////////////////////////////////////////////////////////////////
//                                 User Control Task
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// Set the motors initially
	currentPreset = 0;
	fly(currentPreset);

	while(true)
	{
		// Flywheel Speed
		if(vexRT(Btn8U))
			currentPreset = 0;
		else if (vexRT(Btn8R))
			currentPreset = 1;
		else if (vexRT(Btn8D))
			currentPreset = 2;
		else if (vexRT(Btn8L))
			currentPreset = 3;

		// Set the flywheel speed
		fly(currentPreset);

		// Fit the input to an exponential curve
		// Squares are always positive, so a ternary operator is needed for negative numbers
		// The abs is just in case we decide to go with odd exponents or even roots (like 3/2)
		// We divide by 128 because the program can theoretically reach -128
		int verticalL = pow(abs(vexRT(Ch3))/128.0,2.7)*127.0 *((vexRT(Ch3)>0)?(1):(-1));
		int verticalR = pow(abs(vexRT(Ch2))/128.0,2.7)*127.0 *((vexRT(Ch2)>0)?(1):(-1));

		// Move Robot
		motor[LRW] = verticalL;
		motor[LFW] = motor[LRW];
		motor[RRW] = verticalR;
		motor[RFW] = motor[RRW];

		//Feeder control
		if(vexRT(Btn6U))
			motor[I1] = 127;
		else if(vexRT(Btn5U))
			motor[I1] = -127;
		else
	 	   motor[I1] = 0;
		motor[I2] = motor[I1];
	}
}




/////////////////////////////////////////////////////////////////////////////////////////
//                                 User Defined Functions
/////////////////////////////////////////////////////////////////////////////////////////

// Stop all wheels
void freeze()
{
	motor[LFW] = 0;
	motor[LRW] = 0;
	motor[RFW] = 0;
	motor[RRW] = 0;
}

// Stop all motors on bot
void rest()
{
	freeze();
	fly(0);
	intake(false);
}

void move(int dist)
{
	int distance = abs(dist);
	if(dist>0)
	{
		motor[LFW] = 127;
		motor[LRW] = 127;
		motor[RFW] = 127;
		motor[RRW] = 127;
	}
	else
	{
		motor[LFW] = -127;
		motor[LRW] = -127;
		motor[RFW] = -127;
		motor[RRW] = -127;
	}
	nMotorEncoder[LFW] = 0;
	while(abs(nMotorEncoder[LFW])/627.2<distance/(4.0*PI))
	{
		wait1Msec(10);
	}
	locX+=cosDegrees(rotation)*distance;
	locY+=sinDegrees(rotation)*distance;
	freeze();
}

void rightms(int ms)
{
	motor[LFW] = 60;
	motor[LRW] = 60;
	motor[RFW] = -60;
	motor[RRW] = -60;
	wait1Msec(ms);
	motor[LFW] = -5;
	motor[LRW] = -5;
	motor[RFW] = 5;
	motor[RRW] = 5;
	wait1Msec(5);
	freeze();
}

void leftms(int ms)
{
	motor[LFW] = -60;
	motor[LRW] = -60;
	motor[RFW] = 60;
	motor[RRW] = 60;
	wait1Msec(ms);
	motor[LFW] = 5;
	motor[LRW] = 5;
	motor[RFW] = -5;
	motor[RRW] = -5;
	wait1Msec(5);
	freeze();
}

void forwardms(int ms)
{
	motor[LFW] = 60;
	motor[LRW] = 60;
	motor[RFW] = 60;
	motor[RRW] = 60;
	wait1Msec(ms);
	motor[LFW] = -5;
	motor[LRW] = -5;
	motor[RFW] = -5;
	motor[RRW] = -5;
	wait1Msec(5);
	freeze();
}

void backms(int ms)
{
	motor[LFW] = -60;
	motor[LRW] = -60;
	motor[RFW] = -60;
	motor[RRW] = -60;
	wait1Msec(ms);
	motor[LFW] = 5;
	motor[LRW] = 5;
	motor[RFW] = 5;
	motor[RRW] = 5;
	wait1Msec(5);
	freeze();
}

void rightTurn (int angle)
{
	nMotorEncoder[LFW] = 0;
	motor[LFW] = 60;
	motor[LRW] = 60;
	motor[RFW] = -60;
	motor[RRW] = -60;


	while(nMotorEncoder[LFW]/627.2<(3.125*(angle/360.0)))
	{
		wait1Msec(10);
	}

	rotation = (rotation + angle) % 360;
	freeze();
}

void leftTurn (int angle)
{
	motor[LFW] = -127;
	motor[LRW] = -127;
	motor[RFW] = 127;
	motor[RRW] = 127;

	nMotorEncoder[LFW] = 0;
	while(abs(nMotorEncoder[LFW])/627.2<(3.125*(angle/360.0)))
	{
		wait1Msec(10);
	}

	rotation = (rotation - angle) % 360;
	freeze();
}

void fly(int speedElement)
{
	if(!((speedElement < 0) || (speedElement > 4)))
	{
		if(speedElement == 0)
			drivespeed = 0;
		else
			drivespeed = Presets[speedElement];
	}
	else
		drivespeed = 0;

	motor[REF] = drivespeed;
	motor[RF] = motor[REF];
	motor[LF] = motor[REF];
}

void flyspeed(int speed)
{
	if(!((speed < -128) || (speed > 127)))
	{
		drivespeed = speed;
	}
	else
		drivespeed = 0;

	motor[REF] = drivespeed;
	motor[RF] = motor[REF];
	motor[LF] = motor[REF];
}

void adjustRight()
{
	motor[LFW] = 30;
	motor[LRW] = 30;
	motor[RFW] = -30;
	motor[RRW] = -30;
	/*while(true){
		if(SensorValue(lineTracker)<2850){
		freeze();
		break;
		}*/
}

void adjustLeft()
{
	motor[LFW] = -30;
	motor[LRW] = -30;
	motor[RFW] = 30;
	motor[RRW] = 30;
	/*while(true){
		if(SensorValue(lineTracker)<2850){
		freeze();
		break;
	}*/
}

void intake(bool on)
{
	motor[I1] = (on) ? (127) : (0);
	motor[I2] = motor[I1];
}
