#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           LRWheel,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,           LFWheel,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           RRWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RFWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LFlywheel1,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port8,           LFlywheel2,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           RFlywheel,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,          IntakePuller,  tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	// Set the motors initially
	int Presets[4] = {0, 55, 85, 127};
	int currentPreset = 0;
	motor[LFlywheel1] = Presets[currentPreset];
	motor[LFlywheel2] = motor[LFlywheel1];
	motor[RFlywheel] = motor[LFlywheel2];

	while(true)
	{
		// Flywheel Speed
	 if(vexRT(Btn8U))
		currentPreset = 0;
	 else if (vexRT(Btn8R))
	  currentPreset = 1;
	 else if (vexRT(Btn8D))
	   currentPreset = 2;
	 else if (vexRT(Btn8L))
	   currentPreset = 3;

	  motor[LFlywheel1] = Presets[currentPreset];
	  motor[LFlywheel2] = motor[LFlywheel1];
		motor[RFlywheel] = motor[LFlywheel2];

		// Move Robot
	  motor[LRWheel] = vexRT(Ch3);
	  motor[LFWheel] = motor[LRWheel];
    motor[RRWheel] = vexRT(Ch2);
    motor[RFWheel] = motor[RRWheel];

	   if(vexRT(Btn6U))
	     motor[Intake] = 127;
	 	 else if (vexRT(Btn5U))
	 	   motor[Intake] = 0;

	 	motor[IntakePuller] = motor[Intake];
	}
}
