#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           InsideMotor,   tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           OutsideMotor,  tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int Presets[4] = {0, 26, 44, 74};
	int currentPreset = 0;
	motor[InsideMotor] = Presets[currentPreset];
	motor[OutsideMotor] = motor[InsideMotor];

	while(true)
	{
		if(vexRT(Btn5U))
		{
			if(time1[T1] > 1000)
			{
				if(currentPreset == 0)
					currentPreset = 3;
				else
					currentPreset--;
				clearTimer(T1);
			}
		}
		if(vexRT(Btn6U))
		{
			if(time1[T1] > 1000)
			{
				if(currentPreset == 3)
					currentPreset = 0;
				else
					currentPreset++;
				clearTimer(T1);
			}
		}
		motor[InsideMotor] = Presets[currentPreset];
		motor[OutsideMotor] = motor[InsideMotor];
	}
}
