#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           InsideMotor,   tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           OutsideMotor,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RFWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RBWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LFWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LBWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           IntakeL,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           IntakeR,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int Presets[4] = {0, 26, 44, 74};
	int currentPreset = 0;
	motor[InsideMotor] = Presets[currentPreset];
	motor[OutsideMotor] = motor[InsideMotor];

	while(true)
	{
		 if(vexRT(Btn8U))
			currentPreset = 0;
		 else if (vexRT(Btn8R))
		  currentPreset = 1;
		 else if (vexRT(Btn8D))
		   currentPreset = 2;
		 else if (vexRT(Btn8L))
		   currentPreset = 3;

	   motor[InsideMotor] = Presets[currentPreset];
	   motor[OutsideMotor] = motor[InsideMotor];

	   motor[LBWheel] = vexRT(Ch3);
	   motor[LFWheel] = motor[LBWheel];

	   motor[RBWheel] = vexRT(Ch2);
	   motor[RFWheel] = motor[RBWheel];

	   if(vexRT(Btn6U))
	   {
	     motor[IntakeL] = 26;
	     motor[IntakeR] = 74;
	 	 }

	}
}
